attributes:
  LastSwiftUpdateCheck: '1320'
  LastUpgradeCheck: '1200'
configs:
  Debug: debug
  Release: release
name: iOSApp
options:
  defaultConfig: Debug
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
settings:
  configs:
    Debug:
      GCC_PREPROCESSOR_DEFINITIONS:
      - $(inherited)
      - DEBUG=1
      IPHONEOS_DEPLOYMENT_TARGET: '13.0'
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      SWIFT_VERSION: '5.0'
    Release:
      IPHONEOS_DEPLOYMENT_TARGET: '13.0'
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
      SWIFT_VERSION: '5.0'
targets:
  Domain:
    platform: iOS
    settings:
      configs:
        Debug:
          CLANG_CXX_LANGUAGE_STANDARD: gnu++17
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: 2X6AD4W323
          GCC_PREPROCESSOR_DEFINITIONS:
          - DEBUG=1
          - $(inherited)
          IPHONEOS_DEPLOYMENT_TARGET: '15.0'
          MACOSX_DEPLOYMENT_TARGET: '12.0'
          ONLY_ACTIVE_ARCH: 'YES'
          OTHER_LDFLAGS: -ObjC
          SKIP_INSTALL: 'YES'
          SWIFT_VERSION: '5.0'
          TVOS_DEPLOYMENT_TARGET: '15.0'
        Release:
          CLANG_CXX_LANGUAGE_STANDARD: gnu++17
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: 2X6AD4W323
          IPHONEOS_DEPLOYMENT_TARGET: '15.0'
          MACOSX_DEPLOYMENT_TARGET: '12.0'
          OTHER_LDFLAGS: -ObjC
          SKIP_INSTALL: 'YES'
          SWIFT_VERSION: '5.0'
          TVOS_DEPLOYMENT_TARGET: '15.0'
          VALIDATE_PRODUCT: 'YES'
    sources:
    - path: Domain/Constants.swift
    - name: Model
      path: Domain/Model
    - name: Repository
      path: Domain/Repository
    - name: Stub
      path: Domain/Stub
    type: library.static
  DomainTests:
    dependencies:
    - target: Domain
    - target: libDomain.a
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          CLANG_CXX_LANGUAGE_STANDARD: gnu++17
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: 2X6AD4W323
          GCC_PREPROCESSOR_DEFINITIONS:
          - DEBUG=1
          - $(inherited)
          GENERATE_INFOPLIST_FILE: 'YES'
          IPHONEOS_DEPLOYMENT_TARGET: '15.2'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: dev.fummicc1.ichinen-bingo.Domain.DomainTests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          CLANG_CXX_LANGUAGE_STANDARD: gnu++17
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: 2X6AD4W323
          GENERATE_INFOPLIST_FILE: 'YES'
          IPHONEOS_DEPLOYMENT_TARGET: '15.2'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: dev.fummicc1.ichinen-bingo.Domain.DomainTests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          VALIDATE_PRODUCT: 'YES'
    sources:
    - name: DomainTests
      path: DomainTests
    type: bundle.unit-test
  iOSApp:
    dependencies:
    - target: Domain
    - target: libDomain.a
    platform: iOS
    settings:
      configs:
        Debug:
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: 2X6AD4W323
          INFOPLIST_FILE: iOSApp/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: '15.0'
          MARKETING_VERSION: 1.0.0
          ONLY_ACTIVE_ARCH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: dev.fummicc1.ichinen-bingo.iOSApp
        Release:
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: 2X6AD4W323
          INFOPLIST_FILE: iOSApp/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: '15.0'
          MARKETING_VERSION: 1.0.0
          PRODUCT_BUNDLE_IDENTIFIER: dev.fummicc1.ichinen-bingo.iOSApp
    sources:
    - name: iOSApp
      path: iOSApp
    type: application
