attributes:
  LastUpgradeCheck: '1200'
configs:
  Debug: debug
  Release: release
name: iOSApp
options:
  defaultConfig: Debug
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
settings:
  configs:
    Debug:
      GCC_PREPROCESSOR_DEFINITIONS:
      - $(inherited)
      - DEBUG=1
      IPHONEOS_DEPLOYMENT_TARGET: '13.0'
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      SWIFT_VERSION: '5.0'
    Release:
      IPHONEOS_DEPLOYMENT_TARGET: '13.0'
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
      SWIFT_VERSION: '5.0'
targets:
  Domain:
    platform: iOS
    settings:
      configs:
        Debug:
          INFOPLIST_FILE: Domain/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: dev.fummicc1.ichinen-bingo.Domain
        Release:
          INFOPLIST_FILE: Domain/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: dev.fummicc1.ichinen-bingo.Domain
    sources:
    - headerVisibility: public
      path: Domain/Domain.h
    type: framework
  iOSApp:
    platform: iOS
    settings:
      configs:
        Debug:
          CURRENT_PROJECT_VERSION: '1'
          INFOPLIST_FILE: iOSApp/Info.plist
          MARKETING_VERSION: 1.0.0
          PRODUCT_BUNDLE_IDENTIFIER: dev.fummicc1.ichinen-bingo.iOSApp
        Release:
          CURRENT_PROJECT_VERSION: '1'
          INFOPLIST_FILE: iOSApp/Info.plist
          MARKETING_VERSION: 1.0.0
          PRODUCT_BUNDLE_IDENTIFIER: dev.fummicc1.ichinen-bingo.iOSApp
    sources:
    - name: iOSApp
      path: iOSApp
    type: application
