name: test
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2'
      - name: Install Mint
        run: |
          if !(type "mint" > /dev/null 2>&1)
          then brew install mint
          fi
      - name: Setup Mint
        run: mint bootstrap
      - name: Execute XcodeGen
        run: mint run xcodegen
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Build and test
        run: xcodebuild -scheme iOSApp clean build test -destination "name=iPhone 13" | xcpretty